# Matrix Multiplication

Implement **matrix multiplication** using **Einstein Summation**. Do **NOT** use **`numpy.dot`**.

For matrices $\textbf{A} \in \mathbb{R}^{m \times n}$, $\textbf{B} \in \mathbb{R}^{n \times k}$, the elements $c_{ij}$ of the product $\textbf{C} = \textbf{AB} \in \mathbb{R}^{m \times k}$ are defined as:

$$c_{ij} = \sum_{l=1}^{n} a_{il}b_{lj}$$

$i = 1, ..., m$

$j = 1, ..., k$

In [1]:
import numpy as np

In [2]:
m = 3
k = 4
n = 5

In [3]:
A = np.random.rand(m,n)
B = np.random.rand(n,k)

In [4]:
# Verify array shape
print(A.shape)
print(B.shape)

(3, 5)
(5, 4)


In [5]:
# Use Einstein Summation to find product
C = np.einsum('il,lj',A,B)

In [6]:
# Print array shape
print(C.shape)

(3, 4)


In [8]:
C

array([[1.15511955, 1.32179751, 1.03127936, 1.55748314],
       [0.989661  , 0.81739754, 1.30523196, 1.29505533],
       [0.4385131 , 0.95255747, 0.81770163, 0.94054115]])

In [9]:
np.dot(A,B)

array([[1.15511955, 1.32179751, 1.03127936, 1.55748314],
       [0.989661  , 0.81739754, 1.30523196, 1.29505533],
       [0.4385131 , 0.95255747, 0.81770163, 0.94054115]])

## Example 2.3

For $A = \left[ {\begin{array}{ccc}
1 & 2 & 3\\
3 & 2 & 1\\
\end{array} } \right] \in \mathbb{R}^{2 \times 3}$,$B = \left[ {\begin{array}{cc}
0 & 2\\
1 & -1\\
0 & 1\\
\end{array} } \right] \in \mathbb{R}^{3 \times 2}$, find $AB$ and $BA$

In [10]:
A = np.array([[1,2,3],[3,2,1]])
B = np.array([[0,2],[1,-1],[0,1]])

In [11]:
print(np.dot(A,B))

[[2 3]
 [2 5]]


In [12]:
print(np.dot(B,A))

[[ 6  4  2]
 [-2  0  2]
 [ 3  2  1]]


# Inverse and Transpose

Write a function to calculate inverse of 2 by 2 matrix.

In [13]:
def invMat_two_by_two(A):
    invA = np.copy(A)
    a11 = A[0,0]
    a22 = A[1,1]
    a12 = A[0,1]
    a21 = A[1,0]
    detA = a11*a22 - a12*a21
    invA[0,0] = a22
    invA[1,1] = a11
    invA[0,1] = -1*a12
    invA[1,0] = -1*a21
    invA = 1/detA * invA
    return invA

In [14]:
A = np.array([[1,2],[3,4]])

In [15]:
A

array([[1, 2],
       [3, 4]])

In [16]:
invMat_two_by_two(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [18]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Elementary Transformations

## Row Echelon Form
A matrix is said to be in REF if:
1. All rows that contain only zeros are at the bottom of the matrix. Correspondingly, all rows that contain at least one non-zero element are on top of rows that contain only zeros.
2. Looking at non-zero rows only, the pivot element is always strictly to the right of the pivot of the row above it.

Verify that a matrix is in REF.

In [66]:
A = np.array([[1,3,0,0,3],[0,0,1,0,9],[0,0,0,1,-4]])

In [67]:
A

array([[ 1,  3,  0,  0,  3],
       [ 0,  0,  1,  0,  9],
       [ 0,  0,  0,  1, -4]])

In [83]:
def checkREF(A):
    prev_pivot_index = 0
    curr_pivot_index = 0
    for i in range(A.shape[0]):
        pivot_indices = np.where(A[i,:]!=0)[0]
        if len(pivot_indices) == 0:
            curr_pivot_index = -1
        else:
            curr_pivot_index = pivot_indices[0]
        if i==A.shape[0]-1 and curr_pivot_index==-1:
            return True
        if i!=0 and curr_pivot_index <= prev_pivot_index:
            return False
        prev_pivot_index = curr_pivot_index
    return True

In [85]:
A = np.array([[1,3,0,0,3],[0,0,1,0,9],[0,0,0,0,0]])

In [86]:
A

array([[1, 3, 0, 0, 3],
       [0, 0, 1, 0, 9],
       [0, 0, 0, 0, 0]])

In [87]:
checkREF(A)

True

In [89]:
B = np.array([[1,3,0,0,3],[0,0,0,0,0],[0,1,0,0,0]])

In [90]:
B

array([[1, 3, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [91]:
checkREF(B)

False

In [92]:
C = np.array([[1,3,0,0,3],[0,0,0,0,0],[0,0,0,0,0]])

In [93]:
C

array([[1, 3, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [94]:
checkREF(C)

False

## Row Reduced Echelon Form
A matrix is said to be in RREF if:
1. It is in REF
2. Every pivot is 1
3. The pivot is the only non-zero entry in its column

Verify that a matrix is in RREF

In [107]:
def checkRREF(A):
    # Check if matrix is in REF
    if not checkREF(A):
        return False
    for i in range(A.shape[0]):
        non_zero = np.where(A[i,:]!=0)[0]
        if len(non_zero)>=1:
            pivot = non_zero[0]
            if sum(A[:,pivot]!=0)!=1:
                return False
    return True

In [108]:
A = np.array([[1,3,0,0,3],[0,0,1,0,9],[0,0,0,1,-4]])

In [109]:
A

array([[ 1,  3,  0,  0,  3],
       [ 0,  0,  1,  0,  9],
       [ 0,  0,  0,  1, -4]])

In [110]:
checkREF(A)

True

In [111]:
checkRREF(A)

True

In [112]:
B = np.array([[1,3,0,1,3],[0,0,1,0,9],[0,0,0,1,-4]])

In [113]:
B

array([[ 1,  3,  0,  1,  3],
       [ 0,  0,  1,  0,  9],
       [ 0,  0,  0,  1, -4]])

In [115]:
checkREF(B)

True

In [116]:
checkRREF(B)

False